# Generated by Django 4.2 on 2023-04-26 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='food_category',
            new_name='cd',
        ),
    ]
