# Generated by Django 4.1.3 on 2023-05-17 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_establishments_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='food',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderList',
        ),
    ]
